-- MillSuite Reporting Architecture — Time-Series Foundation
-- Run AFTER base migration and scheduling migration
--
-- Three new tables that convert point-in-time data into trend data.
-- No modifications to existing tables.

-- ═══════════════════════════════════════════════════════════════
-- WEEKLY SNAPSHOTS
-- Auto-generated by /api/weekly-snapshot, stores shop-wide metrics
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS weekly_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,

  -- Shop rate
  shop_rate DECIMAL,
  utilization_assumed DECIMAL DEFAULT 80,
  utilization_actual DECIMAL,

  -- Revenue & costs
  total_revenue DECIMAL DEFAULT 0,
  total_labor_cost DECIMAL DEFAULT 0,
  total_material_cost DECIMAL DEFAULT 0,
  total_overhead DECIMAL DEFAULT 0,
  gross_margin_pct DECIMAL,

  -- Capacity
  headcount INT DEFAULT 0,
  billable_hours DECIMAL DEFAULT 0,
  paid_hours DECIMAL DEFAULT 0,

  -- Projects
  projects_active INT DEFAULT 0,
  projects_shipped INT DEFAULT 0,
  projects_in_production INT DEFAULT 0,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_weekly_snapshots_org_week
  ON weekly_snapshots(org_id, week_start);
CREATE INDEX IF NOT EXISTS idx_weekly_snapshots_org
  ON weekly_snapshots(org_id, week_start DESC);

-- ═══════════════════════════════════════════════════════════════
-- SHOP EVENTS
-- Timestamped events that explain inflection points on charts
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS shop_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  event_date DATE NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'hire', 'departure', 'raise', 'equipment',
    'rate_change', 'capacity_change', 'milestone', 'other'
  )),
  title TEXT NOT NULL,
  description TEXT,
  financial_impact DECIMAL,
  person_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shop_events_org
  ON shop_events(org_id, event_date DESC);

-- ═══════════════════════════════════════════════════════════════
-- PROJECT OUTCOMES
-- Locked financial snapshot when a project completes
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS project_outcomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

  -- Estimates (from spec lines at time of sale)
  estimated_hours DECIMAL DEFAULT 0,
  estimated_materials DECIMAL DEFAULT 0,
  estimated_price DECIMAL DEFAULT 0,

  -- Actuals
  actual_hours DECIMAL DEFAULT 0,
  actual_labor_cost DECIMAL DEFAULT 0,
  actual_materials DECIMAL DEFAULT 0,
  actual_revenue DECIMAL DEFAULT 0,
  actual_margin DECIMAL DEFAULT 0,
  actual_margin_pct DECIMAL DEFAULT 0,

  -- Variances
  hours_variance DECIMAL DEFAULT 0,
  hours_variance_pct DECIMAL DEFAULT 0,
  material_variance DECIMAL DEFAULT 0,
  material_variance_pct DECIMAL DEFAULT 0,

  -- Per-department hours breakdown
  dept_hours_estimated JSONB,
  dept_hours_actual JSONB,

  -- Context at time of completion
  shop_rate_at_completion DECIMAL,
  utilization_at_completion DECIMAL,
  headcount_at_completion INT,

  -- Change orders
  change_order_count INT DEFAULT 0,
  change_order_revenue DECIMAL DEFAULT 0,

  completed_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_project_outcomes_project
  ON project_outcomes(project_id);
CREATE INDEX IF NOT EXISTS idx_project_outcomes_org
  ON project_outcomes(org_id, completed_at DESC);

-- ═══════════════════════════════════════════════════════════════
-- RLS OFF FOR DEV
-- ═══════════════════════════════════════════════════════════════
ALTER TABLE weekly_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_outcomes DISABLE ROW LEVEL SECURITY;

GRANT ALL ON weekly_snapshots TO authenticated, anon;
GRANT ALL ON shop_events TO authenticated, anon;
GRANT ALL ON project_outcomes TO authenticated, anon;
